version: 0.8.0.{build}
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
skip_branch_with_pr: true
environment:
  CI: true
  RUBY_VERSION: 23
  marten_testing_database: "Host=localhost;Port=5432;Database=MartenTests;Username=postgres;Password=Password12!"
  POSTGRES_PATH: C:\Program Files\PostgreSQL\9.5
  PG_PLV8_EXTENSION_ZIP_FILENAME: pg95plv8jsbin_w64
  PG_DB: MartenTests
nuget:
  account_feed: false
  project_feed: true
  disable_publish_on_pr: true

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - ruby --version
  - bundle config --local path vendor/bundle
  - bundle install
  - ps: Install-Product node LTS
  - npm install -g npm
  - npm --version
  - node --version
  - dotnet --version
  - set PATH=%POSTGRES_PATH%\bin;%PATH%
  - curl -L -O -S -s http://www.postgresonline.com/downloads/%PG_PLV8_EXTENSION_ZIP_FILENAME%.zip
  - 7z x %PG_PLV8_EXTENSION_ZIP_FILENAME%.zip
  - xcopy /s /y /d %PG_PLV8_EXTENSION_ZIP_FILENAME% "%POSTGRES_PATH%\"

services:
  - postgresql95

before_build:
  - set PGUSER=postgres
  - set PGPASSWORD=Password12!
  - createdb %PG_DB%
  - psql -d %PG_DB% -c "create extension if not exists plv8;"

build_script:
- cmd: >-
    rake ci
test: off

deploy:
- provider: NuGet
  server: https://www.myget.org/F/jasperfx/api/v2/package
  api_key:
    secure: oszaafgovFR3EwWUTYbLM0MMusfsUDWXmwQnqU0BY8CbE1IZMpUc7qMxn6Fy/1XU
  skip_symbols: true
  on:
    branch:
      - master
      - diagnostics
