version: 0.9.8.{build}
image: Visual Studio 2017


init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
skip_branch_with_pr: true
environment:
  CI: true
  RUBY_VERSION: 23

nuget:
  account_feed: false
  project_feed: true
  disable_publish_on_pr: true

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - ruby --version
  - bundle config --local path vendor/bundle
  - bundle install
  - dotnet --version

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '0.9.8'
  package_version: '0.9.8'
  assembly_version: '0.9.8'
  file_version: '{version}'
  informational_version: '{version}'




build_script:
- cmd: >-
    rake ci version=0.9.8
test: off

deploy:
- provider: NuGet
  server: https://www.myget.org/F/jasperfx/api/v2/package
  api_key:
    secure: oszaafgovFR3EwWUTYbLM0MMusfsUDWXmwQnqU0BY8CbE1IZMpUc7qMxn6Fy/1XU
  skip_symbols: true
  on:
    branch:
      - master
