# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


steps:
- script: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
  displayName: 'Prep Environment'
 
- script: dotnet build Jasper.sln
  displayName: 'Compile Everything'

- script: dotnet test src/Jasper.Testing/Jasper.Testing.csproj --no-restore
  displayName: 'Unit Tests'

- script: dotnet test src/Jasper.TestSupport.Tests/Jasper.TestSupport.Tests.csproj --no-restore
  displayName: 'TestSupport Unit Tests'

- script: 'docker-compose up -d'
  displayName: 'Start Docker Containers'

# - script: dotnet test src/Jasper.RabbitMQ.Tests/Jasper.RabbitMQ.Tests.csproj --no-restore
#  displayName: 'Rabbit MQ Tests'

- script: dotnet test src/Jasper.Persistence.Testing/Jasper.Persistence.Testing.csproj --no-restore
  displayName: 'Persistence Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'xUnit'
    testResultsFiles: '**/TEST-*.xml'
